baseURL = "https://pandora.sh/"
languageCode = "en-us"
title = "Pandora's box"
theme = "hello-friend"
paginate = 5

[params]
  contentTypeName = "posts"
  defaultTheme = "dark"
  showMenuItems = 3
  showReadingTime = true

[languages]
  [languages.en]
    title = "Pandora's Box"
    keywords = "Blog by P. Boonyakarn"
    copyright = "P. Boonyakarn Â© 2018 - 2021 CC-BY"
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "PANDORA'S BOX"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "archive"
        name = "Archive"
        url = "/archive"
